PY3 buster python3 testing BIG commit @1337f284e
See PY3_README for info

This branch is force-pushed (--force-with-lease)

----------------------------------------------------------------
squashed messages:

fixpaths.py working (axis.py unit_str = _(u"\xb0")

glanon.py icons can no longer be array.array()

Error: TypeError: glBitmap() argument 7 must be read-only
       bytes-like object, not array.array

error no longer reported but the bitarrangement/positioning/something
is wrong

testing:
  1) size and positioning are correct for joint mode
     home and limit icons
  2) in world mode, size correct but icons not showing for all axis letters
  3) black,white icons are not all black nor all white
     so something else is wrong

halmodule.cc TypeError unfixed, workaround

workarounds in axis.py
hal_manualtoolchange seems to be broken

wip0-cleanups,inluding accidental .rs274ngc_pre.cc.swp

axis.py use str() putpref (configparser change)

add note about #! line

wip for spartan_handler.py
wip2 for spartan_handler.py

minor trailing white space in big.patch

wip0 (after failed buster test w current patch)

vismach.py fix some tab/space damage

lineardelta.py,rotarydelta.py workaround

use comp[b'item'] instead of comp['item']
for TypeError problem in halmodule.cc (i think)

have current errors like:
TypeError: 'bytes' object is not callable

axis.py:TclCommands():inifindall merge cmd

have not found info on tkinter merge command

wip1 minor prints _task

sai/driver.cc add backtrace support

bin/rs274 should be easier to debug than task in LinuxCNC

wip2 minor

py3_simpletests

wip3 halmodule.cc testing

h[12].py update

wip4 halmodule.cc testing

wip5 hal.py prints

wip6 PY3_README

runtests disable

wip7 PY3_README

wip8 h1.pyminor

halmodule.cc PROGRESS

wip9 restore hal.py

wip10 halmodule.cc some cleanup

wip11 halmodule.cc phal_setattro()

axis.py remove b'item'

hal_manualtoolchange.py update after fixes

wip0 rm py3_simpletests

wip1 PY3_README

wip2 halmodule.cc restores

emcmodule.cc fix get_nmlfile maybe

wip3 emcmodule.cc m_save prints

wip4 just

wip5 just

wip0 minor cleanups

sai/builtin_modules.cc unused file

halmodule.cc missing PyErr_clear (minor)

halmoule.cc return Unicode_AsUTF8 only for

pyhal_read_common and pyhal_write_common

elsewhere use Bytes

axis.py,glcanon.py catch PY3 problem

wip0 minor

wip1 gcodemodule bytes/unicode fixes

PY3_README minor

wip0 some cleanup, some new prints

wip1 rs274ngc remove refs to builtin_module

wip3 taskclass.cc cleanup builtin_module prints

wip4 pango,cairo tests in glnav.py

fix tabs indents damage (4space,no tab)

vismach.py pyvcp_wigets.py vcpparse.py fix tabs/indents damage

axis.py reindent

glnav.py pango,cairo,pangocairo improve, still prob

NotImplementedError: Surface.create_for_data: Not Implemented yet.
what is workaround?

axis.py continue for glnav problem

panelui.c minor cast fix

glnav.py,glcanon.py modify catch messages

wip0 PY3_README minor

yapps for stretch hack

(the yapps package for stretch doesn't work with python3)
see yapps_problems.txt

gcode,hal modules fix cast for g++ (Debian 8.3.0-6)

hal/utils/Submakefile restore for buster py3 default

taskclass.cc tuple segfault python3.7 fix

configure.ac default to work buster python3

hal/utils Submakefile,halcompile.g remove workarounds

taskclass.cc some cleanup

PY3_README updates

debian/configure fix python prints for python3

docs with python in scripts print fixes

docs/src/Submakefile update python print for py3

docs/src/html-latex-images force python2.7

because the python-lxml package in buster isn't
working for python3

wip stray .bak file

taskclass.c rm IGNORE_PYUSABLE, new PY3_WORKAROUND

BOOST_PYTHON_MODULE(interpreter) seems to start

emctaskmain.cc QUIET

wip1 work on interpmodule fail t=0

vismach rm bogus ()

vismach,ldelta,rdelta update for halmodule

wip bwidget prob halui_pvcp working

bwidget.py comment prints

wip1 working on ngcgui/grid/namespace
wip2 namespace is not the problem
wip3 rm some prints etc
wip3 just
wip4 just
wip5 use tkinter.Frame()
wip6 ngcgui ok with tkinter.Frame()
wip7 axis.py, PY3_README updates

wip limit,somelimit(L) home(orig) icons ok

wip0 font import bitmaps
wip1 font_bitmaps.py separate
wip2 font_bitmaps some cleanup
wip3 minor cleanup
wip4 last cleanup for font hack

wip0 update_ini prints,rolfmill superseded

wip1 font_bitmaps reduce descent

wip1 rs274ngc_pre.cc INIT_EXCEPTION msg

Makefile SUPPRESS_WARNINGS env var buster testing